name = "eensy"
version = "0.1.1"
description = "Gleam framework for microprocessor-based embedded systems."
licences = ["Apache-2.0"]


[documentation]
pages = [
    { title = " ", path = "#", source = "" },
    { title = "GPIO guide", path = "guide/02-gpio-guide.html", source = "./pages/guide/02-gpio-guide.md" },
]

[dependencies]
gleam_stdlib = ">= 0.40.0 and < 1.0.0"
gleam_erlang = ">= 0.26.0 and < 1.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
